function result = serviceToOrdinal( service )
%SERVICETOORDINAL Summary of this function goes here
%   Detailed explanation goes here
    if strcmp(service, 'IRC')
        result = 1;
    elseif strcmp(service, 'X11')
        result = 2;
    elseif strcmp(service, 'Z39_50')
        result = 3;
    elseif strcmp(service, 'auth')
        result = 4;
    elseif strcmp(service, 'bgp')
        result = 5;
    elseif strcmp(service, 'courier')
        result = 6;
    elseif strcmp(service, 'csnet_ns')
        result = 7;
    elseif strcmp(service, 'ctf')
        result = 8;
    elseif strcmp(service, 'daytime')
        result = 9;
    elseif strcmp(service, 'discard')
        result = 10;
    elseif strcmp(service, 'domain')
        result = 11;
    elseif strcmp(service, 'domain_u')
        result = 12;
    elseif strcmp(service, 'echo')
        result = 13;
    elseif strcmp(service, 'eco_i')
        result = 14;
    elseif strcmp(service, 'ecr_i')
        result = 15;
    elseif strcmp(service, 'efs')
        result = 16;
    elseif strcmp(service, 'exec')
        result = 17;
    elseif strcmp(service, 'finger')
        result = 18;
    elseif strcmp(service, 'ftp')
        result = 19;
    elseif strcmp(service, 'ftp_data')
        result = 20;
    elseif strcmp(service, 'gopher')
        result = 21;
    elseif strcmp(service, 'hostnames')
        result = 22;
    elseif strcmp(service, 'http')
        result = 23;
    elseif strcmp(service, 'http_443')
        result = 24;
    elseif strcmp(service, 'imap4')
        result = 25;
    elseif strcmp(service, 'iso_tsap')
        result = 26;
    elseif strcmp(service, 'klogin')
        result = 27;
    elseif strcmp(service, 'kshell')
        result = 28;
    elseif strcmp(service, 'ldap')
        result = 29;
    elseif strcmp(service, 'link')
        result = 30;
    elseif strcmp(service, 'login')
        result = 31;
    elseif strcmp(service, 'mtp')
        result = 32;
    elseif strcmp(service, 'name')
        result = 33;
    elseif strcmp(service, 'netbios_dgm')
        result = 34;
    elseif strcmp(service, 'netbios_ns')
        result = 35;
    elseif strcmp(service, 'netbios_ssn')
        result = 36;
    elseif strcmp(service, 'netstat')
        result = 37;
    elseif strcmp(service, 'nnsp')
        result = 38;
    elseif strcmp(service, 'nntp')
        result = 39;
    elseif strcmp(service, 'ntp_u')
        result = 40;
    elseif strcmp(service, 'other')
        result = 41;
    elseif strcmp(service, 'pm_dump')
        result = 42;
    elseif strcmp(service, 'pop_2')
        result = 43;
    elseif strcmp(service, 'pop_3')
        result = 44;
    elseif strcmp(service, 'printer')
        result = 45;
    elseif strcmp(service, 'private')
        result = 46;
    elseif strcmp(service, 'red_i')
        result = 47;
    elseif strcmp(service, 'remote_job')
        result = 48;
    elseif strcmp(service, 'rje')
        result = 49;
    elseif strcmp(service, 'shell')
        result = 50;
    elseif strcmp(service, 'smtp')
        result = 51;
    elseif strcmp(service, 'sql_net')
        result = 52;
    elseif strcmp(service, 'ssh')
        result = 53;
    elseif strcmp(service, 'sunrpc')
        result = 54;
    elseif strcmp(service, 'supdup')
        result = 55;
    elseif strcmp(service, 'systat')
        result = 56;
    elseif strcmp(service, 'telnet')
        result = 57;
    elseif strcmp(service, 'tftp_u')
        result = 58;
    elseif strcmp(service, 'tim_i')
        result = 59;
    elseif strcmp(service, 'time')
        result = 60;
    elseif strcmp(service, 'urh_i')
        result = 61;
    elseif strcmp(service, 'urp_i')
        result = 62;
    elseif strcmp(service, 'uucp')
        result = 63;
    elseif strcmp(service, 'uucp_path')
        result = 64;
    elseif strcmp(service, 'vmnet')
        result = 65;
    elseif strcmp(service, 'whois')
        result = 66;
    else
        result = -1;
    end
end

